import type { ChainId } from "./types";

export type ProductCategory =
  | "basic"
  | "meat"
  | "dry"
  | "produce"
  | "drinks"
  | "household"
  | "pets";

export interface ProductSeed {
  id: string;
  name: string;
  defaultUnit: string;
  packageSize: string;
  category: ProductCategory;
  brand: string;
  prices: Record<ChainId, number>;
  /** Chains where shelf tag shows discount */
  discountAt?: ChainId[];
  /** Loyalty card price (Rimi/Selver/Maxima typical) */
  loyaltyAt?: Partial<Record<ChainId, number>>;
}

/** 36 core products — fictional Eesti hinnad */
export const PRODUCT_SEEDS: ProductSeed[] = [
  // —— Basic food (12) ——
  {
    id: "piim",
    name: "Piim",
    defaultUnit: "1 l",
    packageSize: "1 l",
    category: "basic",
    brand: "Tere",
    prices: { prisma: 0.92, rimi: 0.89, selver: 0.95, maxima: 0.88, lidl: 0.84 },
    discountAt: ["selver"],
    loyaltyAt: { rimi: 0.85, prisma: 0.87 },
  },
  {
    id: "munad",
    name: "Munad",
    defaultUnit: "10 tk",
    packageSize: "10 tk",
    category: "basic",
    brand: "Tallegg",
    prices: { prisma: 2.45, rimi: 2.39, selver: 2.55, maxima: 2.35, lidl: 2.29 },
    loyaltyAt: { rimi: 2.19, maxima: 2.25 },
  },
  {
    id: "leib",
    name: "Rukkileib",
    defaultUnit: "500 g",
    packageSize: "500 g",
    category: "basic",
    brand: "Leibur",
    prices: { prisma: 1.35, rimi: 1.29, selver: 1.39, maxima: 1.19, lidl: 1.15 },
    discountAt: ["maxima"],
    loyaltyAt: { rimi: 1.15 },
  },
  {
    id: "sai",
    name: "Sai",
    defaultUnit: "400 g",
    packageSize: "400 g",
    category: "basic",
    brand: "Fazer",
    prices: { prisma: 0.99, rimi: 1.05, selver: 1.09, maxima: 0.95, lidl: 0.89 },
  },
  {
    id: "või",
    name: "Või",
    defaultUnit: "200 g",
    packageSize: "200 g",
    category: "basic",
    brand: "Valio",
    prices: { prisma: 2.29, rimi: 2.19, selver: 2.35, maxima: 2.09, lidl: 1.99 },
    loyaltyAt: { rimi: 1.99, selver: 2.19 },
  },
  {
    id: "juust",
    name: "Juust Gouda",
    defaultUnit: "200 g",
    packageSize: "200 g",
    category: "basic",
    brand: "Valio",
    prices: { prisma: 2.19, rimi: 2.09, selver: 2.25, maxima: 1.99, lidl: 1.95 },
    loyaltyAt: { maxima: 1.89 },
  },
  {
    id: "hapukoor",
    name: "Hapukoor",
    defaultUnit: "400 g",
    packageSize: "400 g",
    category: "basic",
    brand: "Tere",
    prices: { prisma: 1.45, rimi: 1.39, selver: 1.49, maxima: 1.35, lidl: 1.29 },
    loyaltyAt: { rimi: 1.25 },
  },
  {
    id: "jogurt",
    name: "Jogurt",
    defaultUnit: "400 g",
    packageSize: "400 g",
    category: "basic",
    brand: "Tere",
    prices: { prisma: 0.79, rimi: 0.85, selver: 0.89, maxima: 0.75, lidl: 0.72 },
  },
  {
    id: "kanafilee",
    name: "Kanafilee",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "meat",
    brand: "Tallegg",
    prices: { prisma: 6.99, rimi: 7.19, selver: 6.89, maxima: 7.29, lidl: 6.69 },
    discountAt: ["lidl"],
    loyaltyAt: { selver: 6.49 },
  },
  {
    id: "hakkliha",
    name: "Hakkliha",
    defaultUnit: "500 g",
    packageSize: "500 g",
    category: "meat",
    brand: "Maks& Moorits",
    prices: { prisma: 4.29, rimi: 4.49, selver: 3.99, maxima: 4.19, lidl: 3.89 },
    discountAt: ["selver"],
    loyaltyAt: { selver: 3.69 },
  },
  {
    id: "sink",
    name: "Sink",
    defaultUnit: "200 g",
    packageSize: "200 g",
    category: "meat",
    brand: "Reiv",
    prices: { prisma: 2.69, rimi: 2.59, selver: 2.79, maxima: 2.49, lidl: 2.39 },
  },
  {
    id: "peekon",
    name: "Peekon",
    defaultUnit: "200 g",
    packageSize: "200 g",
    category: "meat",
    brand: "Reiv",
    prices: { prisma: 3.49, rimi: 3.29, selver: 3.69, maxima: 3.19, lidl: 2.99 },
    loyaltyAt: { rimi: 2.89 },
  },
  {
    id: "vorst",
    name: "Vorst",
    defaultUnit: "400 g",
    packageSize: "400 g",
    category: "meat",
    brand: "Linnamäe",
    prices: { prisma: 1.89, rimi: 1.79, selver: 1.95, maxima: 1.85, lidl: 1.75 },
  },
  {
    id: "riis",
    name: "Riis",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "dry",
    brand: "Tilda",
    prices: { prisma: 2.89, rimi: 2.75, selver: 2.95, maxima: 2.65, lidl: 2.59 },
    loyaltyAt: { rimi: 2.49 },
  },
  {
    id: "pasta",
    name: "Pasta",
    defaultUnit: "500 g",
    packageSize: "500 g",
    category: "dry",
    brand: "Barilla",
    prices: { prisma: 1.29, rimi: 0.99, selver: 1.19, maxima: 0.95, lidl: 0.89 },
    discountAt: ["rimi"],
  },
  {
    id: "tatar",
    name: "Tatar",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "dry",
    brand: "Lindström",
    prices: { prisma: 2.29, rimi: 2.19, selver: 2.39, maxima: 2.09, lidl: 1.99 },
  },
  {
    id: "kaerahelbed",
    name: "Kaerahelbed",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "dry",
    brand: "Rolled",
    prices: { prisma: 1.09, rimi: 0.99, selver: 1.15, maxima: 0.95, lidl: 0.89 },
  },
  {
    id: "jahu",
    name: "Jahu",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "dry",
    brand: "Kalev",
    prices: { prisma: 0.89, rimi: 0.85, selver: 0.92, maxima: 0.79, lidl: 0.75 },
  },
  {
    id: "suhkur",
    name: "Suhkur",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "dry",
    brand: "Nordzucker",
    prices: { prisma: 1.09, rimi: 1.05, selver: 1.12, maxima: 0.99, lidl: 0.95 },
    loyaltyAt: { maxima: 0.89 },
  },
  {
    id: "banaan",
    name: "Banaan",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "produce",
    brand: "—",
    prices: { prisma: 1.22, rimi: 1.19, selver: 1.29, maxima: 1.15, lidl: 1.12 },
    discountAt: ["rimi"],
  },
  {
    id: "õun",
    name: "Õun",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "produce",
    brand: "—",
    prices: { prisma: 1.89, rimi: 1.79, selver: 1.95, maxima: 1.69, lidl: 1.65 },
    loyaltyAt: { maxima: 1.49 },
  },
  {
    id: "kartul",
    name: "Kartul",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "produce",
    brand: "—",
    prices: { prisma: 0.72, rimi: 0.69, selver: 0.75, maxima: 0.65, lidl: 0.62 },
    discountAt: ["maxima"],
    loyaltyAt: { rimi: 0.59 },
  },
  {
    id: "kurk",
    name: "Kurk",
    defaultUnit: "1 tk",
    packageSize: "1 tk",
    category: "produce",
    brand: "—",
    prices: { prisma: 0.95, rimi: 0.89, selver: 1.09, maxima: 0.85, lidl: 0.79 },
  },
  {
    id: "tomat",
    name: "Tomat",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "produce",
    brand: "—",
    prices: { prisma: 2.55, rimi: 2.49, selver: 2.69, maxima: 2.39, lidl: 2.29 },
  },
  {
    id: "porgand",
    name: "Porgand",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "produce",
    brand: "—",
    prices: { prisma: 0.99, rimi: 0.95, selver: 1.05, maxima: 0.89, lidl: 0.85 },
  },
  {
    id: "sibul",
    name: "Sibul",
    defaultUnit: "1 kg",
    packageSize: "1 kg",
    category: "produce",
    brand: "—",
    prices: { prisma: 0.89, rimi: 0.85, selver: 0.95, maxima: 0.79, lidl: 0.75 },
  },
  {
    id: "salat",
    name: "Salat",
    defaultUnit: "1 tk",
    packageSize: "1 tk",
    category: "produce",
    brand: "—",
    prices: { prisma: 1.89, rimi: 1.79, selver: 1.99, maxima: 1.69, lidl: 1.59 },
  },
  {
    id: "kohv",
    name: "Kohv",
    defaultUnit: "500 g",
    packageSize: "500 g",
    category: "drinks",
    brand: "Paulig",
    prices: { prisma: 5.49, rimi: 5.29, selver: 5.59, maxima: 4.99, lidl: 4.79 },
    discountAt: ["lidl"],
    loyaltyAt: { rimi: 4.99, prisma: 5.19 },
  },
  {
    id: "tee",
    name: "Tee",
    defaultUnit: "20 tk",
    packageSize: "20 tk",
    category: "drinks",
    brand: "Lipton",
    prices: { prisma: 2.99, rimi: 2.79, selver: 3.19, maxima: 2.69, lidl: 2.59 },
    loyaltyAt: { selver: 2.89 },
  },
  {
    id: "mahl",
    name: "Mahl",
    defaultUnit: "1 l",
    packageSize: "1 l",
    category: "drinks",
    brand: "Aura",
    prices: { prisma: 1.89, rimi: 1.79, selver: 1.99, maxima: 1.69, lidl: 1.59 },
    discountAt: ["lidl"],
  },
  {
    id: "mineraalvesi",
    name: "Mineraalvesi",
    defaultUnit: "1,5 l",
    packageSize: "1,5 l",
    category: "drinks",
    brand: "Vichy",
    prices: { prisma: 0.79, rimi: 0.75, selver: 0.82, maxima: 0.69, lidl: 0.65 },
    loyaltyAt: { rimi: 0.69 },
  },
  {
    id: "wc-paber",
    name: "WC-paber",
    defaultUnit: "8 rulli",
    packageSize: "8 rulli",
    category: "household",
    brand: "Zewa",
    prices: { prisma: 6.49, rimi: 5.99, selver: 6.29, maxima: 5.49, lidl: 4.99 },
    discountAt: ["lidl"],
    loyaltyAt: { rimi: 5.49, maxima: 4.99 },
  },
  {
    id: "pesugeel",
    name: "Pesugeel",
    defaultUnit: "1,5 l",
    packageSize: "1,5 l",
    category: "household",
    brand: "Persil",
    prices: { prisma: 8.49, rimi: 7.99, selver: 8.99, maxima: 7.49, lidl: 6.99 },
    discountAt: ["selver"],
    loyaltyAt: { rimi: 6.99 },
  },
  {
    id: "noudipesuvahend",
    name: "Nõudepesuvahend",
    defaultUnit: "500 ml",
    packageSize: "500 ml",
    category: "household",
    brand: "Fairy",
    prices: { prisma: 2.99, rimi: 2.79, selver: 3.09, maxima: 2.69, lidl: 2.49 },
  },
  {
    id: "kassitoit",
    name: "Kassitoit",
    defaultUnit: "2 kg",
    packageSize: "2 kg",
    category: "pets",
    brand: "Whiskas",
    prices: { prisma: 11.99, rimi: 11.49, selver: 12.49, maxima: 10.99, lidl: 10.49 },
    discountAt: ["maxima"],
    loyaltyAt: { rimi: 10.99 },
  },
  {
    id: "koeratoit",
    name: "Koeratoit",
    defaultUnit: "3 kg",
    packageSize: "3 kg",
    category: "pets",
    brand: "Pedigree",
    prices: { prisma: 13.99, rimi: 13.49, selver: 14.49, maxima: 12.99, lidl: 12.49 },
    loyaltyAt: { selver: 12.99 },
  },
];

export const PRODUCT_SEED_MAP = Object.fromEntries(
  PRODUCT_SEEDS.map((p) => [p.id, p]),
) as Record<string, ProductSeed>;

export const STORE_BY_CHAIN: Record<ChainId, string> = {
  prisma: "prisma-sikupilli",
  rimi: "rimi-ulemiste",
  selver: "selver-jarve",
  maxima: "maxima-lasnamae",
  lidl: "lidl-tahesaju",
};

export const CHAIN_LABEL: Record<ChainId, string> = {
  prisma: "Prisma",
  rimi: "Rimi",
  selver: "Selver",
  maxima: "Maxima",
  lidl: "Lidl",
};
